services:
  db:
    image: postgres:16-alpine
    container_name: wellness_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cursach_db
    ports:
      - "5432:5432"
    volumes:
      - wellness_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cursach_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: wellness_backend
      environment:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/cursach_db?schema=public
        GROQ_API_KEY: ${GROQ_API_KEY}
        PORT: 3001

        JWT_SECRET: ${JWT_SECRET}
        SMTP_HOST: ${SMTP_HOST}
        SMTP_PORT: ${SMTP_PORT}
        SMTP_USER: ${SMTP_USER}
        SMTP_PASS: ${SMTP_PASS}
        SMTP_FROM: ${SMTP_FROM}

        DEBUG_AUTH_NO_EMAIL: "true"

        RSS_IMPORT_MIN_HOURS: 84
        RSS_TIMEZONE: Europe/Moscow
        RSS_LIMIT_PER_FEED: 3
        RSS_IMAGE_DIR: public/images/articles
        RSS_PG_LOCK_KEY: 84512001
      ports:
        - "3001:3001"
      depends_on:
        db:
          condition: service_healthy
      restart: unless-stopped
volumes:
  wellness_pgdata: