import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ibmPlexSans = localFont({
    src: [
        { path: "../fonts/IBMPlexSans-Regular.otf", weight: "400", style: "normal" },
        { path: "../fonts/IBMPlexSans-Medium.otf", weight: "500", style: "normal" },
        { path: "../fonts/IBMPlexSans-Italic.otf", weight: "400", style: "italic" },
    ],
    display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ibmPlexSans.className}>
        {children}
      </body>
    </html>
  );
}
